### ISSUE TITLE
Move to Immutable.JS for faster updates

### ISSUE THREAD

**Issue by jasonmorita** [jasonmorita/react-redux-ui-state#2]
I noticed that using immutablity-helper was slower than Immutable. 

https://jsperf.com/immutability-helper-v-immutablejs

**Comment by jasonmorita** [comment]
Not so sure about this anymore.

**Comment by mrchief** [comment]
Thank you for not adding bloat!

**Comment by jasonmorita** [comment]
@mrchief 👍
