### ISSUE TITLE
Persist state?

### ISSUE THREAD

**Issue by adamcbrewer** [jasonmorita/react-redux-ui-state#3]
Could this be a consideration? Either by default or as an option? 

It would mean not resetting the state when a component is unmounted?

**Comment by jasonmorita** [comment]
Yeah, we could definitely do it as an option in the `config` that gets passed in. Can you do a PR?

**Comment by adamcbrewer** [comment]
In order for the UI State to persist and be recalled by name the uuid suffix should be removed when a config option of `persist` is true.

Have submitted a PR. #4
