### ISSUE TITLE
Updating uiState triggers re-render of separate components

### ISSUE THREAD

**Issue by MoJo600** [jasonmorita/react-redux-ui-state#7]
Good day!

I'm facing an issue where different uiState-wrapped components trigger a re-render whenever the uiState state object is updated. This makes sense, since we're using `immutablity-helper` to return a new copy of the uiState object with the updated sub-states, but the trouble is that I end up with the re-rendering of completely separate components that happen to share in uiState, affecting the performance of my application.

For example, if we have two separate `Component1` and `Component2`:

```javascript
class Component1 extends React.Component {
  constructor(props) {
    super(props);
  }
  onDivClick = () => {
    this.props.setUiState({ uiC1Active: !this.props.uiC1Active  })
  }
  render() {
    return (
      <div onClick={this.onDivClick}>
        <h1> Component 1</h1>
      </div>
    );
  }
}
const uiStateConfig = {
    name: () => `Component1`,
    state: (props) => ({
        uiC1Prop: 'uiProp',
    }),
};

export default connectedComponent1 = compose(
  uiState(uiStateConfig),
)(Component1);
```
And Component2: 

```javascript
class Component2 extends React.Component {
  constructor(props) {
    super(props);
  }
  onDivClick = () => {
    this.props.setUiState({ uiC2Active: !this.props.uiC2Active  })
  }
  render() {
    return (
      <div onClick={this.onDivClick}>
        <h1> Component 2 </h1>
      </div>
    );
  }
}
const uiStateConfig = {
    name: () => `Component2`,
    state: (props) => ({
        uiC2Prop: 'uiProp',
    }),
};
export default connectedComponent2 = compose(
  uiState(uiStateConfig),
)(Component2);
```

Clicking on `Component1`'s div will trigger a re-render for `Component1` as well as `Component2`, and in fact any other components that happen to have their own uiState slice. 

Is this by design, and is there a way get around this?

Thanks!

**Comment by jasonmorita** [comment]
Hi @MoJo600 . This is not by design and was brought to my attention recently. I haven't noticed a performance hit in any apps I have used it in, but in an app with lots of wrapped components mounted at the same time, it could be an issue.

To be honest, I just haven't had time to fix it. But you are welcome to open a PR, it shouldn't be hard to fix.

I think we could use `shouldComponentUpdate` in the HOC to check whether the slice of state for the component in question is different and if not return `false` to prevent a re-render. Somewhere around here: https://github.com/jasonmorita/react-redux-ui-state/blob/master/src/hoc.js#L23-L31

Although I think a deeper re-factor could solve his problem in a more elegant way, it would be more work.

If you want to give a fix a try, that would be great.

If not, I can try to get to it as soon as I can.

Thanks!

**Comment by MoJo600** [comment]
No problem @jasonmorita! Your first suggestion should do the trick, for now. Although I agree, a more stable solution would probably require quite a bit of re-thinking of the design. I've opened a PR implementing this [here](https://github.com/jasonmorita/react-redux-ui-state/pull/8), let me know your thoughts.

**Comment by jasonmorita** [comment]
Closing via https://github.com/jasonmorita/react-redux-ui-state/pull/8

**Comment by jasonmorita** [comment]
I had to revert the PR. Saw some unexpected behavior. Will investigate and post findings here.

**Comment by jasonmorita** [comment]
I should've noticed this from the PR, but the `shouldComponentUpdate` fn in the PR only accounted for `uiState[slice]` changing, but not other props that the component is receiving from other sources, thus preventing re-renders that should take place. Essentially, we'd need to check for uiState diffs, then check for other prop diffs if uiState isEqual.

**Comment by jasonmorita** [comment]
@MoJo600 Do you want to take another crack at this fix? If not, I can add the fix. Thanks!

**Comment by MoJo600** [comment]
@jasonmorita That's true, should've noticed that as well. Go ahead! Got caught up in some private matters over the past week so I couldn't look into it as deeply as I should.

**Comment by jasonmorita** [comment]
Hey @MoJo600 I -think- this will fix the issue. Please verify `npm i react-redux-ui-state@renderfix-b` via https://github.com/jasonmorita/react-redux-ui-state/pull/11

**Comment by MoJo600** [comment]
@jasonmorita I confirmed this fixes the issue, although performance concerns may arise again depending on how flat/complex your component's state may be.
